name: Unit Test

env:
  TF_VERSION: '1.1.7'

on:
  pull_request:
    branches-ignore: []

jobs:
  fmt:
    name: Check Terraform format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format
      run: |
        terraform fmt -check -recursive

  localstack_testing:
    name: localstack testing
    runs-on: ubuntu-latest
    needs:
      - fmt
    defaults:
      run:
        working-directory: local

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Bring up localstack
      run: |
        docker-compose up -d

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Initialize
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -input=false
